name: caddy

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force build even if version exists'
        required: false
        type: boolean
        default: false
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    uses: ./.github/workflows/_docker-build.yml
    with:
      image-name: tgdrive/caddy
      build-context: ./caddy
      upstream-repo: caddyserver/caddy
      version-filter: '.tag_name | .[1:]'
      force: ${{ github.event_name == 'workflow_dispatch' && inputs.force || false }}
    secrets: inherit
