name: hermes-agent

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force build even if version exists'
        required: false
        type: boolean
        default: false
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    uses: ./.github/workflows/_docker-build.yml
    with:
      image-name: tgdrive/hermes-agent
      build-context: ./hermes-agent
      upstream-repo: NousResearch/hermes-agent
      force: ${{ github.event_name == 'workflow_dispatch' && inputs.force || false }}
      upstream-source-repo: NousResearch/hermes-agent
      canonical-dockerfile: hermes-agent/Dockerfile
    secrets: inherit
